server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/loopify?useSSL=false&serverTimezone=UTC
    username: admin
    password: 123456
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: update
