services:
  main-service:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/loopify?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - main-service
      - chat-service
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: loopify
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysql", "-uadmin", "-p123456", "-e", "SELECT 1" ]  # 检查数据库可用性
      interval: 5s
      timeout: 10s
      retries: 30
    networks:
      - app-network
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_connections=1000

  redis:
    image: redis:7.0
    networks:
      - app-network
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.12-management
    networks:
      - app-network
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    networks:
      - app-network
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  app-network:
    driver: bridge