server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
      routes:
        - id: main-service
#          uri: http://main-service:8080 # when it runs docker
          uri: http://localhost:8080 # when it runs local
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**, /api/v1/posts/**

        # route to chat-service
        - id: chat-service
#          uri: http://chat-service:8085 # when it runs docker.
          uri: http://localhost:8085 # when it runs local
          predicates:
            - Path=/api/v1/messages/**, /api/v1/notifications/**, /ws/**

      # global CORS config
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://192.168.31.70:8888" # fronted server address
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allowedHeaders: "*"
            allowCredentials: true # HttpOnly Cookie must true
            maxAge: 3600

# JWT configuration - have to use same secret as JWT was generated
app:
  jwt:
    secret: 8905473032bb464a531e7f1c52a28b6b793f46379f8a8c2d899f30e47325e897fcc7c284005593b242334e6642d5f275c601634ee3d66a02dda7a787064612772dbfc8b599f8d3b4e74a60b564f42ec6a15750c819aa0b59c294b9c8dc51800b6198d2dd6ea0415fc079bf83f6403a2c5f8f029acc092b1e1a120fb805e46e7c3e17b4e7b17632aeaf43f455bac480bc8c1d672bc83e2e86e5daf16ebf1f1be9d9d5b02d6fd97f4c900dc73b6f082a24e6f9e6530f59fc56fb7d20ccf5d73fc7c6b05be5c4f19a50cba77aa406366abf8fe5b98f84e3c3fc5500aec446bf74b806f4c843ad572953463227c24c4ef9ad5cedb3b45779b80c827aabf82f5876f3

  # skip paths
  auth:
    skip-paths: >
      /api/v1/auth/request-code,
      /api/v1/auth/verify-code,
      /api/v1/auth/google/callback,
      /api/v1/auth/refresh,
      /api/v1/auth/logout,
      /actuator/health
      
management:
  metrics:
    enable:
      all: true
      process: false
      system: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.loopify.apigateway: DEBUG