server:
  port: 8085

spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:mysql://localhost:3306/loopify?useSSL=false&serverTimezone=UTC
    username: admin
    password: 123456
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  # Redis Configuration
  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2
  data:
    redis:
      port: 6379
      host: localhost
      timeout: 2000

rabbitmq:
  queue:
    follow-notifications: follow.queue
    comment-notifications: comment.queue

app:
  websocket:
    heartbeat-interval-ms: 30000 # 30 seconds
  redis:
    presence-ttl-seconds: 90

