server:
  port: 8085

spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:mysql://localhost:3306/chat_service_db?useSSL=false&serverTimezone=UTC
    username: admin
    password: 123456
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost
      timeout: 2000

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: chat-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

app:
  websocket:
    heartbeat-interval-ms: 30000 # 30 seconds
  redis:
    presence-ttl-seconds: 90
  kafka:
    topics:
      follow-notifications: follow-notifications-topic
      comment-notifications: comment-notifications-topic

